type=item
matchItems=wooden_sword iron_sword
model=optifine/cit/source_models/2xhand_bita
texture=bita_zwax
nbt.display.Name=iregex:(\u0411\u0438\u0442\u0430\u0020\u0437\u0020\u0446\u0432\u044f\u0445\u0430\u043c\u0438|Bat with nails)