type=item
matchItems=diamond_sword netherite_sword
model=optifine/cit/source_models/2xhand_chaos
texture=chaos
nbt.display.Name=iregex:(\u041a\u043b\u0438\u043d\u043a\u0438\u0020\u0445\u0430\u043e\u0441\u0443|Blades of Chaos)