type=item
matchItems=iron_sword golden_sword diamond_sword netherite_sword
texture=hot_knife
nbt.display.Name=iregex:(\u0420\u043e\u0437\u043a\u0430\u043b\u0435\u043d\u0435 \u043b\u0435\u0437\u043e|Red-hot blade)