type=item
matchItems=iron_sword diamond_sword netherite_sword golden_sword
model=optifine/cit/source_models/2xhand
texture=sabre
nbt.display.Name=iregex:(\u041c\u0435\u0447 \u0410\u0440\u0435\u044f|Sword of Areus)