type=armor
matchItems=chainmail_boots golden_boots iron_boots diamond_boots netherite_boots
texture.iron_layer_1=helmetss
texture.chainmail_layer_1=helmetss
texture.gold_layer_1=helmetss
texture.diamond_layer_1=helmetss
texture.netherite_layer_1=helmetss
nbt.display.Name=iregex:(\u0411\u0435\u0440\u0446\u0456|Tactical boots)