type=armor
matchItems=chainmail_helmet golden_helmet iron_helmet diamond_helmet netherite_helmet
texture.iron_layer_1=helmetss
texture.chainmail_layer_1=helmetss
texture.gold_layer_1=helmetss
texture.diamond_layer_1=helmetss
texture.netherite_layer_1=helmetss
nbt.display.Name=iregex:(\u041d\u0456\u043c\u0435\u0446\u044c\u043a\u0438\u0439 \u0448\u043e\u043b\u043e\u043c|German helmet)