type=item
matchItems=chainmail_helmet golden_helmet iron_helmet diamond_helmet netherite_helmet
texture=helmetss_item
nbt.display.Name=iregex:(\u041d\u0456\u043c\u0435\u0446\u044c\u043a\u0438\u0439 \u0448\u043e\u043b\u043e\u043c|German helmet)