type=armor
matchItems=chainmail_helmet golden_helmet iron_helmet diamond_helmet netherite_helmet
texture.iron_layer_1=m_h
texture.chainmail_layer_1=m_h
texture.gold_layer_1=m_h
texture.diamond_layer_1=m_h
texture.netherite_layer_1=m_h
nbt.display.Name=iregex:(\u0412\u0456\u0439\u0441\u044c\u043a\u043e\u0432\u0438\u0439 \u0448\u043e\u043b\u043e\u043c|Military helmet)