type=armor
matchItems=iron_leggings diamond_leggings netherite_leggings chainmail_leggings golden_leggings
texture.iron_layer_2=jeans
texture.chainmail_layer_2=jeans
texture.gold_layer_2=jeans
texture.diamond_layer_2=jeans
texture.netherite_layer_2=jeans
nbt.display.Name=iregex:(\u0414\u0436\u0438\u043d\u0441\u0438|Jeans)