type=item
matchItems=white_banner light_gray_banner gray_banner black_banner brown_banner red_banner orange_banner yellow_banner lime_banner green_banner cyan_banner light_blue_banner blue_banner purple_banner magenta_banner pink_banner
model=gerflag
texture=gerflag
nbt.display.Name=iregex:(\u041f\u0440\u0430\u043f\u043e\u0440\u0020\u041d\u0456\u043c\u0435\u0447\u0447\u0438\u043d\u0438|Banner of Germany)