type=item
matchItems=white_banner light_gray_banner gray_banner black_banner brown_banner red_banner orange_banner yellow_banner lime_banner green_banner cyan_banner light_blue_banner blue_banner purple_banner magenta_banner pink_banner
model=wheflag
texture=wheflag
nbt.display.Name=iregex:(\u0411\u0456\u043b\u0435 \u0437\u043d\u0430\u043c\u0435\u043d\u043e|White banner)