type=item
matchItems=chainmail_chestplate golden_chestplate iron_chestplate diamond_chestplate netherite_chestplate
texture=green_icon
nbt.display.Name=iregex:(\u041b\u0456\u0441\u043e\u0432\u0438\u0439\u0020\u0448\u0443\u043a\u0430\u0447|Forest explorer)