type=item
matchItems=chainmail_chestplate golden_chestplate iron_chestplate diamond_chestplate netherite_chestplate
texture=kyrtka_icon
nbt.display.Name=iregex:(\u041a\u0443\u0440\u0442\u043a\u0430|Jacket)