type=armor
matchItems=chainmail_chestplate golden_chestplate iron_chestplate diamond_chestplate netherite_chestplate
texture.iron_layer_1=kyrtka
texture.chainmail_layer_1=kyrtka
texture.gold_layer_1=kyrtka
texture.diamond_layer_1=kyrtka
texture.netherite_layer_1=kyrtka
nbt.display.Name=iregex:(\u041a\u0443\u0440\u0442\u043a\u0430|Jacket)