type=armor
matchItems=chainmail_helmet golden_helmet iron_helmet diamond_helmet netherite_helmet
texture.iron_layer_1=green
texture.chainmail_layer_1=green
texture.gold_layer_1=green
texture.diamond_layer_1=green
texture.netherite_layer_1=green
nbt.display.Name=iregex:(\u0428\u043e\u043b\u043e\u043c\u0020\u041c\u0031|M1 Helmet)