type=armor
matchItems=chainmail_boots golden_boots iron_boots diamond_boots netherite_boots
texture.iron_layer_1=portal
texture.chainmail_layer_1=portal
texture.gold_layer_1=portal
texture.diamond_layer_1=portal
texture.netherite_layer_1=portal
nbt.display.Name=iregex:(\u0427\u0435\u0440\u0435\u0432\u0438\u043a\u0438 \u043d\u0435\u0432\u0430\u0433\u043e\u043c\u043e\u0441\u0442\u0456|Long Fall Boots)