type=item
matchItems=iron_sword golden_sword diamond_sword netherite_sword
model=bogomol
texture=bogomol
nbt.display.Name=iregex:(\u041b\u0435\u0437\u0430 \u0431\u043e\u0433\u043e\u043c\u043e\u043b\u0430|Mantis Blades)