type=item
matchItems=stone_pickaxe iron_pickaxe diamond_pickaxe netherite_pickaxe golden_pickaxe
texture=kitchenhammer
nbt.display.Name=iregex:(\u041a\u0443\u0445\u043e\u043d\u043d\u0438\u0439 \u043c\u043e\u043b\u043e\u0442\u043e\u043a|Kitchen hammer)