type=item
matchItems=white_banner light_gray_banner gray_banner black_banner brown_banner red_banner orange_banner yellow_banner lime_banner green_banner cyan_banner light_blue_banner blue_banner purple_banner magenta_banner pink_banner
model=evroflag
texture=evroflag
nbt.display.Name=iregex:(\u0421\u0442\u044f\u0433 \u0404\u0421|Flag of EU)