type=armor
matchItems=iron_leggings diamond_leggings netherite_leggings
texture.iron_layer_2=kebab
texture.diamond_layer_2=kebab
texture.netherite_layer_2=kebab
nbt.display.Name=iregex:(\u0406\u043c\u043f\u043b\u0430\u043d\u0442\u0020\u043b\u044e\u043b\u044f\u002d\u043a\u0435\u0431\u0430\u0431|Cyberware kebab)
