type=item
matchItems=crossbow
model=rialf
model.crossbow_arrow=rialf_arrow
model.crossbow_firework=rialf_arrow
model.crossbow_pulling_0=rialf_pulling_0
model.crossbow_pulling_1=rialf_pulling_1
model.crossbow_pulling_2=rialf_pulling_2
model.crossbow_standby=rialf
nbt.display.Name=iregex:(\u041f\u0456\u0445\u043e\u0442\u043d\u0438\u0439 \u0411\u0435\u0448\u0442\u0440\u0430\u0444\u0435\u0440|Infantry Bestrafer)