type=item
matchItems=crossbow
model=sniper
model.crossbow_arrow=sniper_arrow
model.crossbow_firework=sniper_arrow
model.crossbow_pulling_0=sniper_pulling_0
model.crossbow_pulling_1=sniper_pulling_1
model.crossbow_pulling_2=sniper_pulling_2
model.crossbow_standby=sniper
nbt.display.Name=iregex:(\u0411\u0435\u0448\u0442\u0440\u0430\u0444\u0435\u0440|Bestrafer)