type=item
matchItems=bow
model.bow_standby=m1a1
model.bow_pulling_0=m1a1_pulling_0
model.bow_pulling_1=m1a1_pulling_1
model.bow_pulling_2=m1a1_pulling_2
nbt.display.Name=iregex:(\u0422\u043e\u043c\u043f\u0441\u043e\u043d|Thompson)