type=item
matchItems=bow
model.bow_standby=pm
model.bow_pulling_0=pm_pulling_0
model.bow_pulling_1=pm_pulling_0
model.bow_pulling_2=pm_pulling_0
nbt.display.Name=iregex:(\u041f\u0456\u0441\u0442\u043e\u043b\u0435\u0442 \u041c\u0430\u043a\u0430\u0440\u043e\u0432\u0430|Makarov pistol)