type=item
matchItems=bow
model.bow_standby=water
model.bow_pulling_0=water_pulling_0
model.bow_pulling_1=water_pulling_0
model.bow_pulling_2=water_pulling_0
nbt.display.Name=iregex:(\u0412\u043e\u0434\u044f\u043d\u0438\u0439\u0020\u043f\u0456\u0441\u0442\u043e\u043b\u0435\u0442|Water gun)